var TOKENS=[
{
"username":"abdullah.oguk",
"token":"IGQVJWS0kxWmFTLVBzN0huTlFKcnR6c3ZAsT0h6bm1VMnp2RW5QZAlh1UHJDaFlFMXlOeU1mRkJ2ZA2R0SzYyQ1FRY3pManRncjRqZA3FoRmtrZA0ZAyNXVzS1FiUDM0dElSUXI5TmNkY1o5eWM4NUwtQnlucwZDZD"
},
{
"username":"doganinsesi",
"token":"IGQVJVeTBnWHpRVXByVzVMZAmZA3UnVESmNLdkNacjJITmtRZAXNEOF9mbG1rRFNHZADByUVNRMjAxRGxQcnR4bm9EVG1qQVJMXzJ1ZAktpRUNqUjlRS2tpSWY2Wl83S25TMUhDc1c4dTRvekk3VkZAsSVBCOAZDZD"
}


]

module.exports = { TOKENS }
